// Generates frontend/abi/*.ts from Foundry build output (repo root: `forge build` → out/<Name>.sol/<Name>.json).
// Usage (from frontend/): npm run abi        — run `forge build` in the repo root first.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const frontend = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(frontend, "..", "out");

/** Contract → generated file. `required: false` keeps the existing hand-written file when the contract isn't in the repo yet. */
const CONTRACTS = [
  { name: "ProvenrelyRegistry", file: "registry.ts", exportName: "registryAbi", required: true },
  { name: "SafeSend", file: "safe-send.ts", exportName: "safeSendAbi", required: false },
];

let failed = false;
for (const c of CONTRACTS) {
  const artifact = join(out, `${c.name}.sol`, `${c.name}.json`);
  const target = join(frontend, "abi", c.file);
  if (!existsSync(artifact)) {
    const msg = `${c.name}: no build output at ${relative(frontend, artifact)}`;
    if (c.required) {
      console.error(`✗ ${msg} — run \`forge build\` in the repo root first.`);
      failed = true;
    } else console.warn(`– ${msg}; keeping ${relative(frontend, target)} as is.`);
    continue;
  }
  const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
  if (!Array.isArray(abi)) throw new Error(`${artifact} has no abi array`);
  const src =
    `// Generated by scripts/gen-abi.mjs from forge build output (${c.name}). Do not edit — run \`npm run abi\`.\n` +
    `export const ${c.exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(target, src);
  console.log(`✓ ${relative(frontend, target)} (${abi.length} entries)`);
}
process.exit(failed ? 1 : 0);
