// Generates the contract ABIs from Foundry build output (repo root: `forge build` → out/<Name>.sol/<Name>.json):
//   frontend/abi/*.ts             (typed `as const` for viem)
//   backend/src/abi/*.json        (plain JSON for ethers; only contracts the backend calls)
// Usage (from frontend/): npm run abi        — run `forge build` in the repo root first.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const frontend = join(dirname(fileURLToPath(import.meta.url)), "..");
const root = join(frontend, "..");
const out = join(root, "out");

const CONTRACTS = [
  { name: "ProvenrelyRegistry", file: "registry.ts", exportName: "registryAbi", backend: true },
  { name: "SafeSend", file: "safe-send.ts", exportName: "safeSendAbi", backend: false },
];

let failed = false;
for (const c of CONTRACTS) {
  const artifact = join(out, `${c.name}.sol`, `${c.name}.json`);
  if (!existsSync(artifact)) {
    console.error(`✗ ${c.name}: no build output at ${relative(root, artifact)} — run \`forge build\` in the repo root first.`);
    failed = true;
    continue;
  }
  const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
  if (!Array.isArray(abi)) throw new Error(`${artifact} has no abi array`);

  const target = join(frontend, "abi", c.file);
  writeFileSync(
    target,
    `// Generated by scripts/gen-abi.mjs from forge build output (${c.name}). Do not edit — run \`npm run abi\`.\n` +
      `export const ${c.exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`,
  );
  console.log(`✓ ${relative(root, target)} (${abi.length} entries)`);

  if (c.backend) {
    const backendTarget = join(root, "backend", "src", "abi", `${c.name}.json`);
    mkdirSync(dirname(backendTarget), { recursive: true });
    writeFileSync(backendTarget, JSON.stringify(abi, null, 2) + "\n");
    console.log(`✓ ${relative(root, backendTarget)}`);
  }
}
process.exit(failed ? 1 : 0);
